// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Photos.DataAccess.Data;

#nullable disable

namespace Photos.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbConext))]
    partial class ApplicationDbConextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Photos.Models.Models.Category", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 8,
                            CategoryName = "Krajobraz",
                            DisplayOrder = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Portret",
                            DisplayOrder = 2
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "Natura",
                            DisplayOrder = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
